[package]
name = "proxy2"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
http-body = "0.4"
hyper = "0.14"
hyper-tls = {version = "0.5", features = ["vendored"] }
lambda_runtime = "0.8"
serde = "1.0"
tokio = {version = "1.28", features = ["macros"] }
